language: node_js
node_js:
  - 12

env:
  - CI=true

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn
script:
  - yarn lint
  - yarn format:check
  - yarn typecheck
  - yarn jest
  - yarn mocks &
  - until nc -z 127.0.0.1 4001; do sleep 1 ; done
  - yarn build
  - yarn serve -p8000 &
  - until nc -z 127.0.0.1 8000; do sleep 1 ; done
  - yarn cypress:run:api
  - yarn cypress:run
  - kill $(jobs -p) || true
