language: node_js
node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn
script:
  - yarn lint
  - yarn jest
  - yarn mocks &
  - until nc -z 127.0.0.1 4000; do sleep 1 ; done
  - yarn develop &
  - until nc -z 127.0.0.1 8000; do sleep 1 ; done
  - yarn cypress:run
  - kill $(jobs -p) || true

