language: node_js
node_js:
  - 10

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn
script:
  - yarn jest
  - yarn mocks &
  - until curl -s localhost:4000; do true; done > /dev/null
  - yarn develop &
  - until curl -s localhost:8000; do true; done > /dev/null
  - yarn cypress:test
  - kill $(jobs -p) || true

