language: node_js
node_js:
  - 14

env:
  - CI=true

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install --ignore-engines

script:
  - yarn start-test mock:api "http-get://localhost:4001?query={_empty}" build
  # babel-plugin-remove-graphql-queries requires we test storybook after building Gatsby
  - yarn storybook:build
  - yarn start-server-and-test mock:api "http-get://localhost:4001?query={_empty}" serve 8000 test
  - kill $(jobs -p) || true

notifications:
  email: false
